// generated by Fast Light User Interface Designer (fluid) version 1.0301

#ifndef main_h
#define main_h
#include <FL/Fl.H>
#include "presentation_model.h"
#include <FL/Fl_Double_Window.H>
#include "FL\fl_show_colormap.H"
extern Fl_Double_Window *pStroke_window;
#include <FL/Fl_Value_Slider.H>
extern Fl_Value_Slider *start_radius;
extern Fl_Value_Slider *middle_radius;
extern Fl_Value_Slider *end_radius;
#include <FL/Fl_Button.H>
extern Fl_Button *begin_color;
extern Fl_Button *middle_color;
extern Fl_Button *end_color;
Fl_Double_Window* make_stroke_window();
void save_stroke_settings();
extern Fl_Double_Window *pWindow;
#include "GLPanel.h"
extern GLPanel *pGLPanel;
#include <FL/Fl_Group.H>
#include <FL/Fl_Light_Button.H>
#include <FL/Fl_Color_Chooser.H>
#endif
