// generated by Fast Light User Interface Designer (fluid) version 1.0301

#ifndef main_h
#define main_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "GLPanel.h"
extern GLPanel *pGLPanel;
#include <FL/Fl_Group.H>
#include <FL/Fl_Light_Button.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Color_Chooser.H>
#endif
