// generated by Fast Light User Interface Designer (fluid) version 1.0301

#ifndef obj_layout_h
#define obj_layout_h
#include <FL/Fl.H>
#include<Fl_Native_File_Chooser.h>
Fl_Native_File_Chooser* native_file_opener; 
#include"MainGL.h"
extern MainGL *objviewer;
#include <FL/Fl_Menu_Bar.H>
extern Fl_Menu_Item menu_[];
#endif
