// generated by Fast Light User Interface Designer (fluid) version 1.0301

#include "obj_layout.h"

MainGL *objviewer=(MainGL *)0;

static void cb_file(Fl_Menu_*, void*) {
  native_file_opener->filter("obj file\t*.obj");
if( native_file_opener->show() == 0 ){
   objviewer->load( native_file_opener->filename() );
};
}

Fl_Menu_Item menu_[] = {
 {"file", 0,  (Fl_Callback*)cb_file, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

int main(int argc, char **argv) {
  { objviewer = new MainGL(0, 0, 656, 524, "Obj viewer");
    objviewer->box(FL_FLAT_BOX);
    objviewer->color(FL_BACKGROUND_COLOR);
    objviewer->selection_color(FL_BACKGROUND_COLOR);
    objviewer->labeltype(FL_NO_LABEL);
    objviewer->labelfont(0);
    objviewer->labelsize(14);
    objviewer->labelcolor(FL_FOREGROUND_COLOR);
    objviewer->align(Fl_Align(FL_ALIGN_TOP));
    objviewer->when(FL_WHEN_RELEASE);
    { Fl_Menu_Bar* o = new Fl_Menu_Bar(0, 0, 656, 20);
      o->menu(menu_);
    } // Fl_Menu_Bar* o
    objviewer->end();
    objviewer->resizable(objviewer);
  } // MainGL* objviewer
  objviewer->show(argc, argv);
  return Fl::run();
}
